version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ~/dockerdata/mongodb:/data/db
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    restart: unless-stopped
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
    networks:
      - app-network

  sunwell-bot:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo-express
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge